### ISSUE TITLE
Make Sign-In and Sign-Up Case-Insensitive

### ISSUE THREAD

**Issue by ghost** [nyc-rock-doves-2015/picky_potluck#174]
Problem:
Sign-in is case sensitive.

Behavior:
User tried to make a party and invite me. I'm already a member of Picky Potluck. After she sent the invitation, I got the email, but when I clicked the link, I got "permission denied" on our site.  It also didn't show up as a party in my sidebar.

**Comment by imharrypark** [comment]
I fixed the bug by downcasing email when user signs up and signs in, so there is no conflict anymore.
