### ISSUE TITLE
Extra Allergy Filtering For Hidden Ingredients

### ISSUE THREAD

**Issue by ghost** [nyc-rock-doves-2015/picky_potluck#175]
Need:
Extra filtering of Yummly API allergy categories to ensure that no problematic ingredients appear in carousel.

Behavior:
User marked that she was allergic to soy. She did a search for soup. One of the recipes it returned was miso soup. It calls for miso powder, which contains soy.

**Comment by dmilburn** [comment]
Completed by adding a "related_foods" column to the "nonos" table.
